<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Typ obmedzenia Spomalen premvkaKraj Pre_9f303c</name>
   <tag></tag>
   <elementGuidId>9868934f-f7a5-4551-a0ec-670ac62ecd27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.leaflet-popup-content-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='root']/div/div[2]/div/div/div[6]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-popup-content-wrapper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Typ obmedzenia: Spomalená premávkaKraj: Prešovský krajOkres: PrešovNázov: Rekonštrukcia cesty I/18 LipníkyPopis: Rekonštrukcia cesty I/18 Kapušany - Nemcovce.Status: Oznamuje políciaMeškanie: 0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-dIUggk gBcQIh&quot;]/div[@class=&quot;sc-bdfBwQ gcjelq mr-20 flex-column flex-grow p-5&quot;]/div[@class=&quot;rounded-lg control mt-5 leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom&quot;]/div[@class=&quot;leaflet-pane leaflet-map-pane&quot;]/div[@class=&quot;leaflet-pane leaflet-popup-pane&quot;]/div[@class=&quot;leaflet-popup  leaflet-zoom-animated&quot;]/div[@class=&quot;leaflet-popup-content-wrapper&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='root']/div/div[2]/div/div/div[6]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dopravné obmedzenia'])[2]/following::div[13]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;&lt;'])[1]/following::div[14]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
